name: oshirase_kun
description: お知らせ君 - 予定通知アプリ

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  app_tracking_transparency: ^2.0.6+1
  cloud_firestore: ^5.0.0
  cloud_functions: ^5.6.2
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.0.0
  firebase_auth: ^5.7.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  firebase_remote_config: ^5.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^15.1.3
  google_mobile_ads: ^6.0.0
  http: ^1.2.2
  intl: ^0.20.2
  package_info_plus: ^8.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
